# See: https://circleci.com/docs/2.0/configuration-reference
# See: https://circleci.com/docs/2.0/orb-intro/
# See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: python -m pip install --upgrade pip
      - run: python -m pip install --upgrade pytest
      - run: python -m pip install --upgrade pytest-cov
      - run: python -m pip install --upgrade Sphinx
      - run: python -m pip install --upgrade sphindexer
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run Doctests
          command: python src/__init__.py
      - run:
          name: Run Coverage Tests
          command: pytest --cov=src --cov-report=term-missing tests
      - run:
          name: Report Coverage
          command: coverage report -m
      - run:
          name: Send Report 
          command: codecov

workflows:
  default:
    jobs:
      - build-and-test
