# See: https://circleci.com/docs/2.0/configuration-reference
# See: https://circleci.com/docs/2.0/orb-intro/
# See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: upgrade pip
          command: |
            python -m pip install --upgrade pip
            python -m pip install --upgrade Sphinx
            python -m pip install --upgrade sphindexer
      - run:
          name: Run Doctests
          command: |
            python src/__init__.py
      - run:
          name: Run Tests
          command: |
            coverage run --source=src setup.py test 
      - run:
          name: Report Coverage
            coverage report -m
            codecov

workflows:
  default:
    jobs:
      - build-and-test
