# See: https://circleci.com/docs/2.0/configuration-reference
# See: https://circleci.com/docs/2.0/orb-intro/
# See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: /home/circleci/.pyenv/versions/3.8.12/bin/python3.8 -m pip install --upgrade pip
      - run: /home/circleci/.pyenv/versions/3.8.12/bin/python3.8 -m pip install --upgrade Sphinx
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: coverage run --source=src setup.py test 

workflows:
  sample:
    jobs:
      - build-and-test
